[pytest]
addopts = -q
filterwarnings =
    ignore:.*:urllib3.exceptions.NotOpenSSLWarning
    ignore:.*_register_pytree_node.*:UserWarning:transformers
    ignore:.*SwigPy.*has no module attribute:UserWarning
